version: '{branch}-{build}'
build: off
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: check
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64

    - TOXENV: docs
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64

    - TOXENV: 'py27,codecov'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27

    - TOXENV: 'py27,codecov'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64

    - TOXENV: 'py35,codecov'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35

    - TOXENV: 'py35,codecov'
      TOXPYTHON: C:\Python35-x64\python.exe
      PYTHON_HOME: C:\Python35-x64

    - TOXENV: 'py36,codecov'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36

    - TOXENV: 'py36,codecov'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64

init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*
install:
  - git submodule update --init --recursive
  - '%PYTHON_HOME%\Scripts\pip install --upgrade tox setuptools virtualenv wheel'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'
  - '%PYTHON_HOME%\Scripts\easy_install --version'
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\tox --version'
test_script:
  - '%WITH_COMPILER% %PYTHON_HOME%\Scripts\tox -v'

on_failure:
  - ps: dir "env:"
  - ps: get-content .tox\*\log\*
artifacts:
  - path: dist\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
