Linux:
    Yum:
        Parameters:
            yumrepomap:
                #Amazon:
                -
                    dist: amazon
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-amzn.repo
                #CentOS:
                -
                    dist: centos
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-centos.repo
                #RedHat:
                -
                    dist: redhat
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-rhel.repo
                #SaltEL6:
                -
                    epel_version: 6
                    dist: all
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-salt-el6.repo
                #SaltEL7:
                -
                    epel_version: 7
                    dist: all
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-salt-el7.repo


    Salt:
        Parameters:
            entenv: False
            formulastoinclude:
                - https://s3.amazonaws.com/salt-formulas/systemprep-formula-master.zip
                - https://s3.amazonaws.com/salt-formulas/ash-linux-formula-master.zip
                - https://s3.amazonaws.com/salt-formulas/join-domain-formula-master.zip
                - https://s3.amazonaws.com/salt-formulas/scc-formula-master.zip
                - https://s3.amazonaws.com/salt-formulas/name-computer-formula-master.zip
            formulaterminationstrings:
                - -master
                - -latest
            salt_debug_log: /var/log/saltcall.debug.log
            salt_results_log: /var/log/saltcall.results.log
            saltcontentsource: https://s3.amazonaws.com/systemprep-content/linux/salt/salt-content.zip
            saltinstallmethod: yum
            saltstates: Highstate
            sourceiss3bucket: False
            saltbootstrapsource: None
            saltgitrepo: None
            saltversion: None
            oupath: None
            computername: None

    Custom: None


Windows:
    Salt:
        Parameters:
            saltworkingdir: \SystemContent\Windows\Salt
            saltcontentsource: https://s3.amazonaws.com/systemprep/SystemContent/Windows/Salt/salt-content.zip
            formulastoinclude:
                - https://s3.amazonaws.com/salt-formulas/systemprep-formula-master.zip
                - https://s3.amazonaws.com/salt-formulas/ash-windows-formula-master.zip
                - https://s3.amazonaws.com/salt-formulas/name-computer-formula-master.zip
            formulaterminationstrings:
                - -latest
            ashrole: MemberServer
            computername: None
            entenv: False
            oupath: None
            saltstates: Highstate
