Linux:
    Yum:
        ScriptSource: https://systemprep.s3.amazonaws.com/ContentScripts/systemprep-linuxyumrepoinstall.py
        Parameters:
            yumrepomap:
                #Amazon:
                -
                    dist: amazon
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-amzn.repo
                #CentOS:
                -
                    dist: centos
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-centos.repo
                #RedHat:
                -
                    dist: redhat
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-rhel.repo
                #SaltEL6:
                -
                    epel_version: 6
                    dist: all
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-salt-el6.repo
                #SaltEL7:
                -
                    epel_version: 7
                    dist: all
                    url: https://s3.amazonaws.com/systemprep-repo/linux/yum.repos/systemprep-repo-salt-el7.repo


    Salt:
        ScriptSource: https://systemprep.s3.amazonaws.com/ContentScripts/SystemPrep-LinuxSaltInstall.py
        Parameters:
            entenv: False
            formulastoinclude:
                - https://salt-formulas.s3.amazonaws.com/systemprep-formula-master.zip
                - https://salt-formulas.s3.amazonaws.com/ash-linux-formula-master.zip
                - https://salt-formulas.s3.amazonaws.com/join-domain-formula-master.zip
                - https://salt-formulas.s3.amazonaws.com/scc-formula-master.zip
            formulaterminationstrings:
                - -master
                - -latest
            salt_debug_log: /var/log/saltcall.debug.log
            salt_results_log: /var/log/saltcall.results.log
            saltcontentsource: https://systemprep-content.s3.amazonaws.com/linux/salt/salt-content.zip
            saltinstallmethod: yum
            saltstates: Highstate
            sourceiss3bucket: False
            saltbootstrapsource: None
            saltgitrepo: None
            saltversion: None
            oupath: None

Windows:
    Salt:
        ScriptSource: https://systemprep.s3.amazonaws.com/SystemContent/Windows/Salt/SystemPrep-WindowsSaltInstall.ps1
        Parameters:
            saltworkingdir: "'{0}\\SystemContent\\Windows\\Salt'.format(workingdir)"
            saltcontentsource: https://systemprep.s3.amazonaws.com/SystemContent/Windows/Salt/salt-content.zip
            formulastoinclude:
                - https://salt-formulas.s3.amazonaws.com/systemprep-formula-master.zip
                - https://salt-formulas.s3.amazonaws.com/ash-windows-formula-master.zip
            formulaterminationstrings:
                - -latest
            ashrole: MemberServer
            entenv: False
            saltstates: Highstate
